spring:
application:
name: blog
mvc:
servlet:
path: /blog-service
autoconfigure:
exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
data:
mongodb:
uri: jdbc:mysql://localhost:3306/blog
database: blog